services:

  postgres:
    image: postgres:17
    container_name: sindicato-postgres

    environment:
      POSTGRES_DB: sindicato_intelligence
      POSTGRES_USER: sindicato
      POSTGRES_PASSWORD: sindicato123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:latest
    container_name: sindicato-n8n-dev

    ports:
      - "5678:5678"

    environment:
      N8N_SECURE_COOKIE: "false"
      GENERIC_TIMEZONE: Europe/Madrid
      N8N_BLOCK_ENV_ACCESS_IN_NODE: "false"
      BACKEND_N8N_AUTH_EMAIL: n8n@sindicato.es
      BACKEND_N8N_AUTH_PASSWORD: Admin@123

    volumes:
      - n8n_data:/home/node/.n8n

  mailhog:
    image: mailhog/mailhog:latest
    container_name: sindicato-mailhog

    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
  n8n_data: