spring.application.name=intelligence
spring.jpa.open-in-view=true
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
